config/routes.rb
UpToSpeed::Application.routes.draw do

  match '/auth/:provider/callback' => 'sessions#sign_in'
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#sign_out', :as => :signout

  match '/stats' => 'users#stats'

  resources :users do
    get 'levels_info', :on => :member
  end

  resources :events do
    member do
      get 'new_attendees'
      post 'register_attendees'
      post 'attend'
    end
  end

  resources :learnings, :workouts

  root :to => 'events#index'
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :events, :through => :attendances
  has_many :attendances
  has_many :workouts
  has_many :learnings

  belongs_to :office

  validates :email, :presence => true, :uniqueness => true

  def name
    "#{first_name} #{last_name}"
  end

  def events_learnings_and_workouts_this_month
    (workouts.this_month + learnings.this_month + events.past_this_month).reverse
  end

  def all_events_learnings_and_workouts
    { "Workouts" => workouts.count, "Learnings" => learnings.count, "Events" => events.count }
  end

  def self.create_with_omniauth(auth)
    create! do |user|
      user.first_name = auth["info"]["first_name"]
      user.last_name = auth["info"]["last_name"]
      user.email = auth["info"]["email"]
      user.provider = auth["provider"]
      user.uid = auth["uid"]
    end
  end

end

app/controllers/users_controller.rb
require "uptospeed/level"
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def show
    set_back_url
    @user = User.find(current_user.id)
    @duration = @user.events.past.map(&:duration).sum / 3600
    @total_points = Event.total(Time.now)
    @level = Level.new(@total_points)
    @percentage = (Float(@level.start_level - @total_points) / (@level.start_level - @level.next_level)) * 100
  end

  def edit
    @user = User.find(params[:id])
    @offices = Office.all
    @locales = [[t(:'locales.en'), "en"], [t(:'locales.sv'), "sv"]]
  end

  def update
    @user = User.find(params[:id])

    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to users_path
  end

  def stats
    @month_before_last = Event.total(2.months.ago.beginning_of_month)
    @last_month = Event.total(1.months.ago.beginning_of_month)
    @this_month = Event.total(Time.now.beginning_of_month)
  end

  def log_out
    session[:user_id] = nil
    redirect_to root_path
  end

  def levels_info; end
end

app/helpers/users_helper.rb
module UsersHelper
  def level_theme(level)
    if level.level < 7
      return "ui-body-f"
    elsif level.level < 10
      return "ui-body-e"
    else
      return "ui-body-g"
    end
  end
end

app/views/users/_form.html.erb
<%= form_for @user, :'data-ajax' => "false", :'data-transition' => "flip", :'data-direction' => "reverse" do |f| %>
    <% if @user.errors.any? %>
    <div id="error_explanation">
        <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

        <ul>
            <% @user.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
    <% end %>
    <ul data-role="listview" data-inset="true" data-theme="c">
        <li data-role="fieldcontain" class="row">
            <%= f.label :first_name, t(:'users.edit.first_name') %>
            <%= f.text_field :first_name %>
        </li>
        <li data-role="fieldcontain" class="row">
            <%= f.label :last_name, t(:'users.edit.last_name') %>
            <%= f.text_field :last_name %>
        </li>
        <li data-role="fieldcontain" class="row ui-body-b">
            <%= f.label :office_id, t(:'users.edit.office') %>
            <%= f.select :office_id, options_from_collection_for_select(@offices, :id, :i18n_title, f.object.office_id), :include_blank => t(:'users.edit.choose_office') %>
        </li>
        <li data-role="fieldcontain" class="row">
            <%= f.label :locale, t(:'users.edit.locale') %>
            <%= f.select :locale, options_for_select(@locales, f.object.locale), {}, :'data-theme' => "c" %>
        </li>
        <li data-role="fieldcontain" class="actions">
            <%= f.submit t(:'shared.forms.save'), :'data-theme' => "g" %>
        </li>
    </li>
<% end %>

app/views/users/_level.html.erb
<div class="level">
	<div class="info-header shadow <%= level_theme(@level) %>">
		<%= link_to t(:'users.show.information.whats_this'), levels_info_user_path(current_user), :'data-role' => "button", :'data-rel' => "dialog", :'data-icon' => "info", :'data-iconpos' => "notext", :class => "ui-btn-left float-left pos-abs" %>
		<h1>Level <%= @level.level %></h1>
	</div>
	<div class="content ui-body-d shadow">
		<div class="ui-grid-a">
		    <div class="ui-block-a points"><%= raw t(:'levels.total_points', :total_points => @total_points) %></div>
		    <% if @level.level < 10 %>
		    	<div class="ui-block-b next-level"><%= raw t(:'levels.next_level', :next_level_points => @level.next_level - @level.points) %></div>
		    <% end %>
		</div>
	    <div class="graph parent ui-body-a">
	        <div class="graph <%= level_theme(@level) %>" style="width:<%= @percentage %>%"></div>
	    </div>
	</div>
</div>

app/views/users/admin.html.erb
<table>
    <thead>
        <td>Month</td>
        <td>Points</td>
    </thead>
    <tbody>
        <tr>
            <td><%= 2.months.ago.strftime("%B") %></td>
            <td><%= @month_before_last %></td>
        </tr>
        <tr>
            <td><%= 1.months.ago.strftime("%B") %></td>
            <td><%= @last_month %></td>
        </tr>
        <tr>
            <td><%= Time.now.strftime("%B") %></td>
            <td><%= @this_month %></td>
        </tr>
    </tbody>
</table>

app/views/users/edit.html.erb
<div data-role="header">
    <%= link_to t(:'shared.back'), user_path(@user), :'data-role' => "button", :'data-transition' => "flip", :'data-direction' => "reverse", :'data-icon' => "delete", :'data-iconpos' => "notext" %>
    <h1 data-title="Up to Speed"><%= t(:'users.edit.header') %></h1>
</div>
<div data-role="content" data-theme="b">
    <%= render :partial => "form" %>
</div>

app/views/users/index.html.erb
<div data-role="header">
    <h1 data-title="Up to Speed">Users</h1>
</div>
<div data-role="content">
    <p>Find me in app/views/users/index.html.erb</p>
</div>

app/views/users/levels_info.html.erb
<div data-role="header" data-position="fixed">
    <h1 data-title="Up to Speed">Levels</h1>
</div>
<div data-role="content" class="ui-body-b">
    <p><%= t(:'levels.explanation') %></p>
    <p><%= t(:'levels.pay_out') %></p>
    <ol class="levels-legend">
        <li><%= t(:'levels.points', :points => 0) %></li>
        <li><%= t(:'levels.points', :points => 9) %></li>
        <li><%= t(:'levels.points', :points => 38) %></li>
        <li><%= t(:'levels.points', :points => 85) %></li>
        <li><%= t(:'levels.points', :points => 150) %></li>
        <li><%= t(:'levels.points', :points => 235) %></li>
        <li class="mid"><%= t(:'levels.points', :points => 375) %></li>
        <li class="mid"><%= t(:'levels.points', :points => 462) %></li>
        <li class="mid"><%= t(:'levels.points', :points => 620) %></li>
        <li class="full"><%= t(:'levels.points', :points => 750) %></li>
    </ol>
    <p class="light"><%= t(:'levels.disclaimer') %></p>
</div>
<%= render :partial => "/notification", :locals => { :flash => flash } %>

app/views/users/show.html.erb
<div data-role="header" data-position="fixed">
    <h1 data-title="Up to Speed"><%= @user.name %></h1>
    <%= link_to t(:'users.show.settings'), edit_user_path(@user), :'data-role' => "button", :'data-transition' => "flip", :'data-icon' => "gear", :'data-iconpos' => "notext", :class => "ui-btn-right" %>
</div>
<div data-role="content" class="ui-body-b">
    <%= render :partial => "level" %>

    <% if @user.events.future.present? %>
        <ul data-role="listview" data-inset="true" data-theme="d">
            <li data-role="list-divider"><%= t(:'events.future_events') %> <span class="ui-li-count"><%= @user.events.future.count %></span></li>
            <% @user.events.future.each do |event| %>
                <li>
                    <%= link_to event_path(event, :url => request.url), :'data-transition' => "pop" do %>
                        <div class="ui-grid-a">
                            <div class="ui-block-a">
                                <%= event.title %>
                            </div>
                            <div class="ui-block-b right-content">
                                <%= l event.start_time, :format => :shorter %>
                            </div>
                        </div>
                    <% end %>
                </li>
            <% end %>
        </ul>
    <% end %>

    <ul data-role="listview" data-inset="true" data-theme="d" data-content-theme="c">
        <li data-role="list-divider"><%= t(:'events.all_types_this_month') %> <span class="ui-li-count"><%= @user.events_learnings_and_workouts_this_month.count %></span></li>
        <% @user.events_learnings_and_workouts_this_month.each do |event| %>
            <li>
                <div class="ui-grid-a">
                    <div class="ui-block-a">
                        <%= event.title %>
                    </div>
                    <div class="ui-block-b right-content">
                        <%= l event.start_time, :format => :shorter %>
                    </div>
                </div>
            </li>
        <% end %>
    </ul>
    <ul data-role="listview" data-inset="true" data-theme="d" data-content-theme="c">
        <li data-role="list-divider"><%= t(:'events.all_types_history') %></li>
        <% @user.all_events_learnings_and_workouts.each do |type, count| %>
            <li>
                <div class="ui-grid-a">
                    <div class="ui-block-a">
                        <%= type %>
                    </div>
                    <div class="ui-block-b right-content">
                        <%= count %>
                    </div>
                </div>
            </li>
        <% end %>
    </ul>
</div>
<%= render :partial => "/notification", :locals => { :flash => flash } %>
<%= render :partial => "/main_navigation" %>

app/views/users/stats.html.erb
<table>
    <thead>
        <td>Month</td>
        <td>Points</td>
    </thead>
    <tbody>
        <tr>
            <td><%= 2.months.ago.strftime("%B") %></td>
            <td><%= @month_before_last %></td>
        </tr>
        <tr>
            <td><%= 1.months.ago.strftime("%B") %></td>
            <td><%= @last_month %></td>
        </tr>
        <tr>
            <td><%= Time.now.strftime("%B") %></td>
            <td><%= @this_month %></td>
        </tr>
    </tbody>
</table>