config/routes.rb
UpToSpeed::Application.routes.draw do

  match '/auth/:provider/callback' => 'sessions#sign_in'
  match '/auth/failure' => 'sessions#failure'
  match '/signout' => 'sessions#sign_out', :as => :signout

  match '/stats' => 'users#stats'

  resources :users do
    get 'levels_info', :on => :member
  end

  resources :events do
    member do
      get 'new_attendees'
      post 'register_attendees'
      post 'attend'
    end
  end

  resources :learnings, :workouts

  root :to => 'events#index'
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :users, :through => :attendances
  has_many :attendances
  belongs_to :office

  validates :google_id, :presence => true, :uniqueness => true
  validates :title, :presence => true
  validates :where, :presence => true

  scope :past, lambda { where("start_time < ?", Time.now) }
  scope :future, lambda { where("start_time > ?", Time.now) }
  scope :this_month, lambda { where("start_time > ?", Time.now.beginning_of_month) }
  scope :past_this_month, lambda { where("start_time > ?", Time.now.beginning_of_month).past }
  scope :old, lambda { where("start_time < ?", Time.now.beginning_of_month) }

  def duration
    end_time - start_time
  end

  def group_by_date
    start_time.to_date
  end

  def google_event
    @google_event ||= GCal4Ruby::Event.find(Event.auth_google_service, :id => google_id)
  end

  def self.total(time = Time.now)
    this_month = {:created_at => time.beginning_of_month..time.end_of_month}
    Attendance.where(this_month).count + Workout.where(this_month).count + Learning.where(this_month).count
  end

  def self.exists_before?(time)
    Event.order(:start_time).limit(1).first.start_time < time.beginning_of_week
  end

  def self.exists_after?(time)
    Event.order(:start_time).reverse_order.limit(1).first.start_time > time.end_of_week
  end

  def self.fetch_events_from_google(args = {})
    start_at = args[:start_at].present? ? args[:start_at] : Time.now.beginning_of_week
    end_at = args[:end_at].present? ? args[:end_at] : Time.now.end_of_week

    service = Event.auth_google_service
    events = GCal4Ruby::Event.find(service, "", {
      "recurrence-expansion-start"  => start_at.utc.xmlschema,
      "start-min"                   => start_at.utc.xmlschema,
      "recurrence-expansion-end"    => end_at.utc.xmlschema,
      "start-max"                   => end_at.utc.xmlschema,
      "ctz"                         => "Europe/Stockholm",
      "singleevents"                => true
    })
    calendar_id = fetch_calendar(service).id
    events.select!{|e| e.calendar_id == calendar_id}.sort!{|a,b| a.start_time <=> b.start_time}
    events.each do |event|
      event.attendees.delete_if {|a| a[:name] =~ /Up to Speed Stockholm/}
    end
  end

  def self.auth_google_service
    @service ||= begin
      service = GCal4Ruby::Service.new
      service.authenticate(ENV['UPTOSPEED_USERNAME'], ENV['UPTOSPEED_PASSWORD'])
      service
    end
  end

  def self.fetch_calendar(service = nil)
    unless service.present?
      service = auth_google_service
    end
    service.calendars.select{|cal| cal.title =~ /Up to Speed Stockholm/}.first
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  helper_method :weekend?

  def index
    now = params[:now].present? ? Time.parse(params[:now]) : Time.now
    if weekend?(now)
      start_date = now.beginning_of_day
      end_date = (now + 1.weeks).end_of_week
    else
      start_date = now.beginning_of_week
      end_date = now.end_of_week
    end
    if current_user.office.present?
      @events_grouped = current_user.office.events.where("start_time > ? and end_time < ?", start_date, end_date).order("start_time ASC").group_by(&:group_by_date)
      if !@events_grouped.has_key?(Time.now.to_date) && @events_grouped.present?
        date_range = (start_date.to_date..@events_grouped.keys.last)
        if date_range.cover?(Time.now.to_date)
          today = {Time.now.to_date => []}
          @events_grouped.merge!(today)
          new_hash = {}
          @events_grouped.keys.sort.map{|date| new_hash[date] = @events_grouped[date]}
          @events_grouped = new_hash
        end
      end
    end
    @learning = Learning.new(:user => current_user)
    @workout = Workout.new(:user => current_user)
    set_back_url
  end

  def show
    @event = Event.find(params[:id])
  end

  def attend
    if Attendance.create_or_destroy_by_params(params)
      redirect_to Event.find(params[:id])
    else
      redirect_to Event.find(params[:id]), notice: 'Nagot gick fel, forsok igen'
    end
  end

  def new_attendees
    @event = Event.find(params[:id])
    if current_user.office_id
      @users = User.where(:office_id => current_user.office_id).order(:first_name)
    else
      @users = User.all.order(:first_name)
    end
  end

  def register_attendees
    @event = Event.find(params[:id])
    @event.users << User.find(params[:attendees].keys)
    @event.save
    redirect_to @event
  end

  private
  def weekend?(date)
    date.wday == 6 or date.wday == 0
  end
end

app/helpers/events_helper.rb
# -*- encoding: utf-8 -*-
module EventsHelper
  def future_events_params
    now = params[:now].present? ? Time.parse(params[:now]) : Time.now
    now = (now + 1.weeks).to_date
    { now: now }
  end

  def past_events_params
    now = params[:now].present? ? Time.parse(params[:now]) : Time.now
    now = (now - 1.weeks).to_date
    { now: now }
  end

  def now_from_params
    params[:now].present? ? Time.parse(params[:now]) : Time.now
  end

  def exists_after?(time)
    if weekend?(time)
      Event.exists_after?(time + 1.weeks)
    else
      Event.exists_after?(time)
    end
  end

  def exists_before?(time)
    if weekend?(time)
      Event.exists_before?(time + 1.weeks)
    else
      Event.exists_before?(time)
    end
  end

  def geo?(event)
    event.lat.present? and event.lng.present?
  end

  def old?(event)
    event.start_time.end_of_day < Time.now
  end

  def today?(date)
    " today" if date == Time.now.to_date
  end

  def places(address)
    return "Sats Medborgarplatsen"        if address =~ /Kocksgatan 12/
    return "Eriksdalsbadet"               if address =~ /Hammarby Slussväg 20/
    return "Mynewsdesk Stockholmskontor"  if address =~ /Rosenlundsgatan 40/
    return "Fryshuset"                    if address =~ /Mårtensdalsgatan 6/
    return "VBC Sportcenter"              if address =~ /Södermalmsallen 14/
  end
end

app/views/events/_event.html.erb
<li id="event<%= event.id %>" class="event<%= event.users.include?(current_user) ? " you" : "" %><%= old?(event) ? " old" : "" %>">
    <%= link_to event_path(event.id, :url => request.fullpath), :'data-transition' => "pop" do %>
        <h3><%= event.title %></h3>
        <p><%= places(event.where) %></p>
        <p class="ui-li-aside event-time"><strong><%= event.start_time.to_s(:time) %> - <%= event.end_time.to_s(:time) %></strong></p>
        <span class="ui-li-count attending-amount<%= event.users.count == 0 ? " not-visible" : "" %>"><%= event.users.count %></span>
    <% end %>
</li>

app/views/events/_event_list.html.erb
<li class="event<%= event.users.include?(current_user) ? " you" : "" %><%= old ? " old" : "" %>">
    <%= link_to event_path(event.id, :url => request.url), :'data-rel' => "dialog", :'data-transition' => "pop" do %>
        <h3><%= event.title %></h3>
        <p><%= event.where %></p>
        <p class="ui-li-aside event-time"><strong><%= event.start_time.to_s(:time) %> - <%= event.end_time.to_s(:time) %></strong></p>
        <% if event.users.present? %>
            <span class="ui-li-count attending-amount"><%= event.users.count %></span>
            <%= ring(:event => event) %>
        <% end %>
    <% end %>
    <%= link_to "Se!", event_path(event.id, :url => request.url), :'data-rel' => "dialog", :'data-transition' => "pop" %>
</li>

app/views/events/index.html.erb
<div data-role="header" data-position="fixed">
    <% if exists_before?(now_from_params) %>
        <%= link_to t(:'shared.previous'), events_path(past_events_params), :'data-role' => "button", :'data-direction' => "reverse", :'data-icon' => "arrow-l", :'data-iconpos' => "notext" %>
    <% end %>
    <h1 data-title="<%= t(:title) %>"><%= t(:'events.header') %></h1>
    <% if exists_after?(now_from_params) %>
        <%= link_to t(:'shared.next'), events_path(future_events_params), :'data-role' => "button", :'data-icon' => "arrow-r", :'data-iconpos' => "notext", :class => "ui-btn-right" %>
    <% end %>
</div>
<div class="ui-grid-a ui-body-a">
    <div class="ui-block-a">
        <%= form_for @workout, :'data-ajax' => "false" do |f| %>
            <%= f.hidden_field :user_id %>
            <%= f.submit t(:'workouts.create'), :'data-theme' => "g" %>
        <% end %>
    </div>
    <div class="ui-block-b">
        <%= form_for @learning, :'data-ajax' => "false" do |f| %>
            <%= f.hidden_field :user_id %>
            <%= f.submit t(:'reads.create'), :'data-theme' => "g" %>
        <% end %>
    </div>
</div>
<div data-role="content" data-theme="c">
    <% if @events_grouped.present? %>
        <div id="events">
            <ul data-role="listview" data-divider-theme="b" data-split-theme="c" data-split-icon="arrow-r">
                <% @events_grouped.each do |date, events| %>
                    <li data-role="list-divider" role="heading" class="<%= date.strftime("%A").downcase %><%= date.     end_of_day < Time.now ? " old" : "" %><%= today?(date) %>"><%= l date, :format => :list %></    li>
                    <% events.each do |event| %>
                        <%= render :partial => "event", :locals => { :event => event } %>
                    <% end %>
                <% end %>
            </ul>
        </div>
    <% else %>
        <div class="center-content no-events">
            <p class="light"><%= t(:'events.no_events.description') %></p>
            <p class="light"><%= t(:'events.no_events.update_settings') %></p>
        </div>
    <% end %>
</div>
<%= render :partial => "/notification", :locals => { :flash => flash } %>
<%= render :partial => "/main_navigation" %>

app/views/events/new_attendees.html.erb
<div data-role="header" data-position="fixed">
    <h1 data-title="Up to Speed">Vilka mer?</h1>
</div>
<div data-role="content" class="ui-body-b">
    <div data-role="fieldcontain">
        <%= form_tag register_attendees_event_path do %>
            <fieldset>
                <% @users.each do |user| %>
                    <%= check_box_tag "attendees[#{user.id}]", user.id, @event.users.include?(user), :disabled => @event.users.include?(user), :'data-theme' => (@event.users.include?(user) ? "b" : "d") %>
                    <%= label_tag "attendees[#{user.id}", user.name %>
                <% end %>
            </fieldset>
            <%= submit_tag "Spara" %>
        <% end %>
    </div>
</div>
<%= render :partial => "/notification", :locals => { :flash => flash } %>

app/views/events/show.html.erb
<div data-role="header" data-position="inline">
    <%= link_to t(:'shared.close'), back_button_url, :'data-role' => "button", :'data-icon' => "delete", :'data-transition' => "pop", :'data-direction' => "reverse", :'data-iconpos' => "notext", :class => "remove-text left-close-button" %>
    <h1 data-title="<%= t(:title) %>"><%= @event.title %></h1>
    <% if geo?(@event) %>
        <%= link_to t(:'events.map'), map_event_path(@event), :'data-role' => "button", :'data-transition' => "flip", :'data-icon' => "map", :'data-iconpos' => "notext", :class => "ui-btn-right" %>
    <% end %>
</div>
<div id="event" data-role="content" data-theme="b">
    <div class="event-info-wrapper clearfix">
        <h3 class="float-left"><%= places(@event.where) %></h3>
        <p class="time float-right"><strong><%= @event.start_time.to_s(:time) %> - <%= @event.end_time.to_s(:time) %></strong></p>
    </div>
    <% if @event.content.present? %>
        <div class="info-header ui-body-e shadow">
            <h2><%= t(:'shared.info') %></h2>
        </div>
        <div class="content ui-body-d shadow">
            <%= simple_format(@event.content) %>
        </div>
    <% end %>
    <% if @event.users.present? %>
        <ul data-role="listview" data-inset="true" data-theme="d">
            <li data-role="list-divider" role="heading" data-theme="a">
                <%= t(:'events.attendances.header') %>
                <% if @event.users.include?(current_user) && @event.start_time < Time.now %>
                    <%= link_to "Register attendees", new_attendees_event_path, :id => 'register-attendees', :class => 'list-divider-button', :'data-theme' => "c", :'data-role' => "button", :'data-mini' => "true", :'data-icon' => "plus", :'data-iconpos' => "notext", :'data-rel' => "dialog" %>
                <% end %>
            </li>
            <% @event.users.each do |user| %>
                <li>
                    <%= user.name %>
                </li>
            <% end %>
        </ul>
    <% else %>
        <h3><%= t(:'events.attendances.no_attendees') %></h3>
    <% end %>
    <%= form_tag attend_event_path(@event.id), :'data-ajax' => "false" do %>
        <%= hidden_field_tag :user_id, current_user.id.to_s %>
        <%= hidden_field_tag :attending, !@event.users.include?(current_user) %>
        <% if @event.users.include?(current_user) %>
            <% if old?(@event) %>
                <p class="points-received"><strong><%= t(:'events.points_received') %></strong></p>
            <% else %>
                <p><strong><%= t(:'events.attendances.you') %></strong></p>
            <% end %>
        <% else %>
            <p><strong><%= t(:'events.attendances.will_you') %></strong></p>
        <% end %>
        <% if @event.users.include?(current_user) %>
            <%= submit_tag t(:'events.attendances.decline'), :'data-theme' => "f", :'data-icon' => "delete" %>
        <% else %>
            <%= submit_tag t(:'events.attendances.accept'), :'data-theme' => "g", :'data-icon' => "check" %>
        <% end %>
        <%= link_to t(:'shared.cancel'), back_button_url, :'data-role' => "button", :'data-icon' => "back", :'data-theme' => "c", :'data-transition' => "pop", :'data-direction' => "reverse" %>
    <% end %>
</div>